language: java
jdk: openjdk8
script:
  - jdk_switcher use openjdk8
  - # do stuff with OpenJDK 10
  - export JAVA_HOME=$HOME/openjdk8
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk8 --target $JAVA_HOME
  - # do stuff with open OpenJDK 11
