language: java
jdk: openjdk8
script:
  - jdk_switcher use openjdk8
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
cache:
  directories:
  - "$HOME/.m2"
notifications:
   slack: sunbird-ci:UegIg4Bf86V3HcXAB2uXNLGI
   on_success: never
   on_failure: always
   email:
     recipients:
      - manzarul.07@gmail.com
     on_success: never
     on_failure: always
